export interface Product {
  id: number;
  name: string;
  category: 'vegetables' | 'dairy' | 'poultry' | 'staples';
  price: number;
  unit: string;
  rating: number;
  reviewsCount: number;
  deliveryEstimate: string;
  hasPickup: boolean;
  isPopular: boolean;
  minOrder: number;
  availableQty: number;
  imageUrl: string;
  badge?: string;
  origin: string; // e.g. "La Paz Farm", "Buenavista Valley" - shown in order detail/login
}

export const CATALOG_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Fresh Cow Milk (Glass Bottle)',
    category: 'dairy',
    price: 95,
    unit: '1L Bottle',
    rating: 4.9,
    reviewsCount: 142,
    deliveryEstimate: 'Tomorrow, 6-9 AM',
    hasPickup: true,
    isPopular: true,
    minOrder: 2,
    availableQty: 60,
    badge: 'Farm Fresh Daily',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    origin: 'Buenavista Dairy Hills',
  },
  {
    id: 2,
    name: 'Native Red Tomatoes (Kamatis)',
    category: 'vegetables',
    price: 120,
    unit: 'kg',
    rating: 4.8,
    reviewsCount: 230,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: true,
    minOrder: 5,
    availableQty: 150,
    badge: 'Top Seller',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    origin: 'La Paz Agricultural Farm',
  },
  {
    id: 3,
    name: 'Fresh Purple Eggplant (Talong)',
    category: 'vegetables',
    price: 80,
    unit: 'kg',
    rating: 4.7,
    reviewsCount: 88,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: true,
    minOrder: 5,
    availableQty: 100,
    badge: 'Crisp & Sweet',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    origin: 'La Paz Valley Crops',
  },
  {
    id: 4,
    name: 'Farm Fresh Eggs (Tray of 30)',
    category: 'poultry',
    price: 220,
    unit: 'Tray (30 pcs)',
    rating: 4.9,
    reviewsCount: 310,
    deliveryEstimate: 'Same day or tomorrow',
    hasPickup: true,
    isPopular: true,
    minOrder: 1,
    availableQty: 80,
    badge: 'Large Brown',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80',
    origin: 'Agusan Poultry Estate',
  },
  {
    id: 5,
    name: 'Golden Squash (Kalabasa)',
    category: 'vegetables',
    price: 60,
    unit: 'kg',
    rating: 4.6,
    reviewsCount: 75,
    deliveryEstimate: 'In 2 Days',
    hasPickup: false,
    isPopular: true,
    minOrder: 5,
    availableQty: 120,
    badge: 'Long Shelf Life',
    imageUrl: 'https://images.unsplash.com/photo-1570586437263-ab629fccc818?auto=format&fit=crop&w=600&q=80',
    origin: 'Reyes Highlands',
  },
  {
    id: 6,
    name: 'Crisp Red Onions (Sibuyas)',
    category: 'staples',
    price: 110,
    unit: 'kg',
    rating: 4.8,
    reviewsCount: 164,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: true,
    minOrder: 3,
    availableQty: 200,
    badge: 'Firm & Pungent',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    origin: 'Northern Mindanao Growers',
  },
  {
    id: 7,
    name: 'Green Bell Peppers (Atsuete / Capsicum)',
    category: 'vegetables',
    price: 140,
    unit: 'kg',
    rating: 4.7,
    reviewsCount: 52,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: false,
    minOrder: 2,
    availableQty: 50,
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80',
    origin: 'Buenavista Valley',
  },
  {
    id: 8,
    name: 'Round Green Cabbage (Repolyo)',
    category: 'vegetables',
    price: 75,
    unit: 'kg',
    rating: 4.5,
    reviewsCount: 61,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: false,
    minOrder: 5,
    availableQty: 90,
    imageUrl: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=600&q=80',
    origin: 'La Paz Mountain Slope',
  },
  {
    id: 9,
    name: 'White Clean Potatoes (Patatas)',
    category: 'staples',
    price: 90,
    unit: 'kg',
    rating: 4.6,
    reviewsCount: 94,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: false,
    isPopular: false,
    minOrder: 5,
    availableQty: 180,
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    origin: 'Bukidnon-Butuan Link',
  },
  {
    id: 10,
    name: 'Native Dried Garlic Bulbs (Bawang)',
    category: 'staples',
    price: 130,
    unit: 'kg',
    rating: 4.9,
    reviewsCount: 118,
    deliveryEstimate: 'Tomorrow morning',
    hasPickup: true,
    isPopular: false,
    minOrder: 2,
    availableQty: 85,
    badge: 'Aromatic',
    imageUrl: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=600&q=80',
    origin: 'Caraga Agro Co-op',
  },
];
